# (who, EN, KO, screen)
SEGS = [
("0. 콜드 오픈 (인사보다 먼저 강한 질문·숫자)", [
("K","Fifteen million foreigners visited Korea in just eight months. A record.","외국인 1,500만 명이 8개월 만에 한국을 찾았어요. 사상 최대예요.","전체화면 카운터 0→15.05M, 세계 지도에서 한국으로 화살표가 모임"),
("Kangfree","And they didn't just visit. They caught something.","그런데 그냥 온 게 아니에요. 뭔가에 걸렸어요.","투샷"),
("K","It's called \"Seoul fever.\"","\"서울병\"이라고 부릅니다.","큰 글자 SEOUL FEVER, 온도계가 올라감 (효과음: 팝)"),
("K","Hello, world. I'm Master K, and this is the Four Eyes Report.","안녕하세요, 세계. 마스터 K입니다. 포 아이즈 리포트예요.","투샷 + 로고"),
("Kangfree","Coming up: a fever, a chip boom, a holiday for an alphabet, and why Koreans ask your age.","오늘은 열병, 반도체 호황, 알파벳을 위한 휴일, 그리고 한국인이 왜 나이부터 묻는지를 다룹니다.","투샷, 꼭지 이름 4개가 차례로 팝업"),
]),
("1. Seoul fever (Ms. Nonfic 등장)", [
("K","Let's start with the fever. Please welcome Ms. Nonfic. As in non-fiction.","열병부터 시작하죠. Ms. Nonfic을 소개합니다. 논픽션 할 때 그 논픽이에요.","게스트샷 하드 컷, 이름표"),
("Nonfic","I don't do fiction. January to August: fifteen point oh five million foreign visitors.","저는 허구는 안 합니다. 1월부터 8월까지 외국인 방문객 1,505만 명.","카운터 15.05M, 라벨 \"Jan–Aug 2026, record\""),
("Kangfree","That's more people than live in Pennsylvania!","펜실베이니아 주 인구보다 많아요!","비교 막대: 15.05M vs 펜실베이니아 약 13M"),
("Nonfic","August alone: two point two five million. Also a record.","8월 한 달만 225만 명. 이것도 최고 기록입니다.","막대 2.25M, \"RECORD\" 도장"),
("K","A big share came from Southeast Asia, helped by easier entry rules and higher spending.","동남아시아에서 많이 왔어요. 입국 규정이 쉬워지고 쓰는 돈도 늘었고요.","지도: 동남아 → 서울 화살표"),
("Kangfree","Hello, Singapore, Malaysia, and the Philippines! We see you!","싱가포르, 말레이시아, 필리핀 안녕하세요! 보고 있어요!","투샷"),
("K","Now the new word. \"Seoul fever,\" and its cousin, \"Busan fever.\" It's what travelers feel after they go home.","새로 생긴 말이에요. \"서울병\", 그리고 사촌 격인 \"부산병\". 여행에서 돌아간 뒤 느끼는 증상입니다.","카드: SEOUL FEVER / BUSAN FEVER"),
("Kangfree","So it's homesickness. For a place that isn't your home.","그러니까 향수병인데, 내 집이 아닌 곳에 대한 향수병이네요.","투샷"),
("Nonfic","A ranking agrees: Seoul is number four in Asia for repeat travel.","순위도 같은 이야기를 합니다. 서울은 아시아에서 재방문 여행지 4위입니다.","순위 막대 #4 강조"),
("Kangfree","Number four! Who beat us?","4위요! 누가 우리를 이겼어요?","투샷"),
("Nonfic","I don't guess.","저는 추측 안 합니다.","게스트샷"),
("K","Symptoms include booking your second trip before the first one ends.","증상으로는 첫 여행이 끝나기 전에 두 번째 여행을 예약하는 것이 있습니다.","투샷"),
("Nonfic","Treatment: none known.","치료법: 알려진 바 없음.","게스트샷"),
]),
("2. 지금 서울에서 볼 것 (Prof. Indoor 등장)", [
("K","If you catch it, where do you go? Our travel expert: Professor Indoor. Self-certified. Online.","걸렸다면 어디로 갈까요? 여행 전문가 Professor Indoor입니다. 자칭. 온라인으로.","게스트샷 하드 컷, 이름표"),
("Indoor","I've been there!","저 거기 가 봤어요!","게스트샷"),
("K","Physically?","몸으로요?","투샷"),
("Indoor","...Emotionally.","...마음으로요.","게스트샷"),
("Indoor","Okay, facts. Seoul is running a welcome campaign for tourists through October eleventh.","좋아요, 사실입니다. 서울시가 10월 11일까지 관광객 환영 캠페인을 하고 있어요.","카드: SEOUL WELCOME WEEK, 9/19–10/11"),
("Kangfree","What does a welcome campaign even do?","환영 캠페인이 뭘 해 주는데요?","투샷"),
("Indoor","Help desks near Myeongdong Station, with interpretation in English, Chinese, and Japanese.","명동역 근처 안내 데스크에서 영어, 중국어, 일본어 통역을 해 줘요.","지도: 명동 핀 + 언어 3개 아이콘"),
("K","And October seventh to eleventh, the K-Royal Culture Festival turns the five grand palaces into stages.","그리고 10월 7일부터 11일까지는 K-로열 문화 축제가 5대 궁을 무대로 바꿉니다.","지도: 5대 궁 + 종묘 핀 (K+화면)"),
("Indoor","And there's a moonlight tour of Changdeokgung, with sessions in English.","창덕궁 달빛 기행도 있고, 영어 회차도 있어요.","AI 일러스트: 달빛 아래 궁궐"),
("Kangfree","A palace at night. That's so romantic.","밤의 궁궐이라니. 너무 낭만적이에요.","투샷"),
("Indoor","I watched the whole thing on a live stream.","저는 전부 라이브로 봤어요.","게스트샷"),
("Kangfree","From your couch?","소파에서요?","투샷"),
("Indoor","Best seat in the house.","가장 좋은 자리죠.","게스트샷"),
("Indoor","And the souvenir of the season is a cap. Seoul's city brand teamed up with a traditional-knot design brand.","이번 시즌 기념품은 모자예요. 서울시 브랜드가 전통 매듭 디자인 브랜드와 손잡았어요.","AI 일러스트: 매듭 장식 모자"),
("Indoor","One post about it got two point seven million views on Japanese social media. No ads.","그 게시물 하나가 일본 SNS에서 270만 조회를 기록했어요. 광고도 없이요.","카운터 2.7M views + NO ADS"),
("K","A city made a hat go viral without paying for it.","도시가 돈 한 푼 안 쓰고 모자를 유행시켰네요.","투샷"),
]),
("3. 수출 사상 최대 (Max Rise 등장)", [
("K","Now, another record. Max Rise, money and business.","이번엔 또 다른 기록입니다. 돈과 사업 담당, Max Rise입니다.","게스트샷 하드 컷, 이름표"),
("Rise","Max Rise. As in: numbers go up. And they did.","Max Rise. 숫자가 오른다는 뜻이죠. 그리고 정말 올랐어요.","게스트샷"),
("K","September exports.","9월 수출입니다.","카드: SEPTEMBER EXPORTS"),
("Rise","One hundred twenty point nine billion dollars. A monthly record. Up eighty-three point five percent from a year ago.","1,209억 달러. 월간 사상 최고입니다. 1년 전보다 83.5% 늘었어요.","막대 애니메이션 66→121 (십억 달러), +83.5%"),
("Kangfree","Eighty-three percent?! That's almost double!","83%요?! 거의 두 배잖아요!","투샷"),
("K","The star is chips. Semiconductor exports hit sixty point three billion dollars, up two hundred sixty-three percent.","주인공은 반도체예요. 반도체 수출이 603억 달러로 263% 늘었습니다.","도넛 차트: 반도체 ≈ 전체 수출의 절반 (K+화면)"),
("Kangfree","Chips are almost half of everything Korea sells abroad?","반도체가 한국이 해외에 파는 것의 거의 절반이에요?","투샷"),
("Rise","Almost half. AI data centers need memory chips, and Korea makes a lot of them.","거의 절반이에요. AI 데이터센터에 메모리 반도체가 필요한데, 한국이 많이 만들거든요.","AI 일러스트: 데이터센터와 칩"),
("K","January to September: eight hundred fourteen point five billion dollars. That's already more than all of last year, seven hundred nine billion.","1~9월 합계는 8,145억 달러예요. 이미 작년 한 해 7,093억 달러보다 많습니다.","막대 2개: 2025 전체 vs 2026 1~9월 (K+화면)"),
("Rise","On track for one trillion dollars. Limit up!","1조 달러를 향해 가는 중입니다. 상한가!","카운터 $1 TRILLION (효과음)"),
("Kangfree","A trillion! How many zeros is that?","1조 달러! 영이 몇 개예요?","투샷"),
("K","Twelve. Thank you for the math.","열두 개요. 계산 고마워요.","투샷"),
("Rise","Seoul fever. Chip fever. Limit up!","서울병. 반도체병. 상한가!","게스트샷"),
("Kangfree","Is there a cure?","치료법은 없어요?","투샷"),
("Rise","Not on my chart.","제 차트엔 없습니다.","게스트샷"),
]),
("4. 한글날 (K + Kangfree)", [
("K","A holiday you might not know: Hangul Day, October ninth.","모를 수도 있는 휴일이 있어요. 10월 9일 한글날입니다.","카드: HANGUL DAY, OCT 9"),
("Kangfree","A holiday for an alphabet?","알파벳을 위한 휴일이요?","투샷"),
("K","Yes. Korea takes a day off to celebrate its writing system.","네. 한국은 문자를 기념하려고 하루를 쉽니다.","투샷"),
("Kangfree","Imagine America taking a day off for the letter A.","미국이 A라는 글자를 위해 하루 쉰다고 상상해 보세요.","투샷"),
("K","King Sejong the Great created it in the fourteen-forties, so ordinary people could read and write.","세종대왕이 1440년대에 만들었어요. 보통 사람들이 읽고 쓸 수 있도록요.","타임라인 1446 + 실루엣 일러스트 (K+화면)"),
("Kangfree","And before that?","그 전에는요?","투샷"),
("K","Scholars wrote in Chinese characters. Learning them took years.","학자들은 한자로 썼어요. 배우는 데 몇 년이 걸렸죠.","투샷"),
("K","Hangul's consonants copy the shape your mouth and tongue make when you say them.","한글 자음은 소리를 낼 때 입과 혀의 모양을 본떴어요.","애니메이션: ㄱ ㄴ ㅁ 글자와 입 모양 단면도 (K+화면)"),
("Kangfree","The letters are diagrams? That's genius!","글자가 그림 설명서라고요? 천재적이에요!","투샷"),
("K","Today there are twenty-four letters: fourteen consonants and ten vowels.","지금은 24자예요. 자음 14개, 모음 10개.","카운터 14 + 10 = 24 (K+화면)"),
("Kangfree","Learners say you can learn to read it in a day.","하루면 읽는 법을 배울 수 있다고들 해요.","투샷"),
("K","Let me test that. Write your name.","시험해 보죠. 이름을 써 보세요.","투샷"),
("Kangfree","Done!","다 썼어요!","한글로 쓴 이름 카드"),
("K","That says \"Kang-peu-ri.\" Close enough.","\"강프리\"라고 쓰였네요. 그 정도면 됐어요.","투샷"),
]),
("5. 왜 나이부터 물을까 (K + Kangfree)", [
("Kangfree","Last topic. A question every foreigner hears within five minutes.","마지막 주제예요. 외국인이 5분 안에 듣게 되는 질문이에요.","투샷"),
("K","\"How old are you?\"","\"몇 살이세요?\"","큰 글자 HOW OLD ARE YOU?"),
("Kangfree","In Korea, that's grammar.","한국에서는 그게 문법이에요.","투샷"),
("K","Korean has speech levels. To pick the right one, you need to know who's older.","한국어에는 말투 단계가 있어요. 알맞은 말투를 고르려면 누가 연장자인지 알아야 하죠.","말투 단계 사다리 그래픽"),
("Kangfree","So it's not nosy. It's a setting.","그러니까 참견이 아니라 설정값이네요.","투샷"),
("K","Until 2023, Korea had a \"Korean age\": you're one at birth, and everyone gets a year older every January first.","2023년까지는 \"한국 나이\"가 있었어요. 태어나면 한 살, 그리고 1월 1일마다 모두 한 살씩 늘죠.","타임라인 애니메이션: 12/31 출생=1세 → 1/1=2세 (K+화면)"),
("Kangfree","So a baby born on December thirty-first is two the next day?","그럼 12월 31일에 태어난 아기가 다음 날 두 살이에요?","투샷"),
("K","Technically, yes.","원칙적으로는 그렇죠.","투샷"),
("K","In June 2023, Korea switched official documents to international age.","2023년 6월, 한국은 공식 문서의 나이를 만 나이로 통일했어요.","카드: JUNE 2023"),
("Kangfree","So everyone got younger overnight!","그럼 모두가 하룻밤에 어려진 거네요!","투샷"),
("K","By one or two years. Yes.","한두 살씩이요. 맞아요.","투샷"),
("Kangfree","Best law ever.","최고의 법이에요.","투샷"),
("K","Social life didn't change. People still ask.","사회생활은 안 바뀌었어요. 사람들은 여전히 물어봐요.","투샷"),
("Kangfree","One more thing. Koreans say \"our.\" Our mom, our house, our school. Even \"our wife.\"","하나 더요. 한국인은 \"우리\"라고 말해요. 우리 엄마, 우리 집, 우리 학교. 심지어 \"우리 아내\"까지요.","큰 글자 OUR 로 단어 모음"),
("K","It's not ownership. It's belonging. \"Our\" means \"we share this.\"","소유가 아니라 소속이에요. \"우리\"는 \"함께 나눈다\"는 뜻이죠.","투샷"),
("Kangfree","So he's not sharing his wife. He's sharing the word.","그러니까 아내를 나눠 쓰는 게 아니라 단어를 나눠 쓰는 거네요.","투샷"),
("K","Please don't say that in English.","영어로는 제발 그렇게 말하지 마세요.","투샷"),
]),
("6. K's Take + 엔딩", [
("K","So here's my take. Fifteen million visitors, a record chip boom, an alphabet with its own holiday. Different stories, same pattern: the world is showing up for Korea.","제 생각은 이렇습니다. 방문객 1,500만 명, 사상 최대 반도체 호황, 휴일까지 있는 문자. 서로 다른 이야기지만 하나의 흐름이에요. 세계가 한국을 찾아오고 있다는 것.","투샷"),
("K","And Korea's answer is very Korean: \"Welcome. Our home is your home.\"","그리고 한국의 대답은 아주 한국적입니다. \"어서 오세요. 우리 집은 당신 집이에요.\"","투샷"),
("Kangfree","Tell us in the comments: what's the first thing you'd ask a Korean?","댓글로 알려 주세요. 한국 사람에게 제일 먼저 뭘 묻고 싶으세요?","투샷"),
("K","Subscribe, and we'll see you Wednesday. Stay curious. Keep your lenses clean.","구독하시고, 수요일에 만나요. 계속 궁금해하세요. 렌즈는 깨끗하게.","투샷"),
]),
]
