# (who, EN, KO, screen)   who: K, Kangfree = hosts; Nonfic, Indoor, Rise, Hidden (Dr. H), Joe = desk experts
SEGS = [
("0. 콜드 오픈 (인사보다 먼저 강한 질문·숫자)", [
("K","Fifteen million foreigners visited Korea in just eight months. A record.","외국인 1,500만 명이 8개월 만에 한국을 찾았어요. 사상 최대예요.","전체화면 카운터 0→15.05M, 세계 지도에서 한국으로 화살표가 모임"),
("Kangfree","And they didn't just visit. They caught something.","그런데 그냥 온 게 아니에요. 뭔가에 걸렸어요.","투샷"),
("K","It's called \"Seoul fever.\"","\"서울병\"이라고 부릅니다.","큰 글자 SEOUL FEVER, 온도계가 올라감 (효과음: 팝)"),
("K","Hello, world. I'm Master K, and this is the Four Eyes Report.","안녕하세요, 세계. 마스터 K입니다. 포 아이즈 리포트예요.","투샷 + 로고"),
("Kangfree","Coming up: a fever, a chip boom, a holiday for an alphabet, a very fast country, and why Koreans ask your age.","오늘은 열병, 반도체 호황, 알파벳을 위한 휴일, 아주 빠른 나라, 그리고 한국인이 왜 나이부터 묻는지를 다룹니다.","투샷, 꼭지 이름 5개가 차례로 팝업"),
]),
("1. Seoul fever (Ms. Nonfic 진행 설명)", [
("K","Let's start with the fever. Our current affairs correspondent, Ms. Nonfic. She reads the corrections page for fun.","열병부터 시작하죠. 시사 담당 Ms. Nonfic입니다. 정정 기사 코너를 취미로 읽는 분이에요.","게스트샷 하드 컷, 이름표"),
("Nonfic","Good evening. From January to August, fifteen point oh five million foreign visitors came to Korea. A record. That is more people than live in Pennsylvania. Pennsylvania has not commented.","안녕하십니까. 1월부터 8월까지 외국인 방문객 1,505만 명이 한국에 왔습니다. 사상 최대입니다. 펜실베이니아 주 인구보다 많습니다. 펜실베이니아는 입장을 밝히지 않았습니다.","게스트+화면: 카운터 15.05M, 비교 막대 vs 펜실베이니아 약 13M"),
("Kangfree","Somebody call Pennsylvania!","누가 펜실베이니아에 전화 좀 해 봐요!","투샷"),
("Nonfic","August alone: two point two five million. Another record. Much of the growth came from Southeast Asia, thanks to easier entry rules and higher spending.","8월 한 달만 225만 명. 또 최고 기록입니다. 성장의 상당 부분은 동남아시아에서 왔고, 입국 규정이 쉬워지고 소비가 늘어난 덕분입니다.","게스트+화면: 막대 2.25M + RECORD 도장, 지도: 동남아 → 서울"),
("Kangfree","Hello, Singapore, Malaysia, and the Philippines! We see you!","싱가포르, 말레이시아, 필리핀 안녕하세요! 보고 있어요!","투샷"),
("K","And a new word came with them. \"Seoul fever,\" and its cousin, \"Busan fever.\"","그리고 새로운 말도 같이 왔어요. \"서울병\", 그리고 사촌 격인 \"부산병\".","카드: SEOUL FEVER / BUSAN FEVER"),
("Nonfic","Both words describe travelers who miss the city after they go home. In other words: repeat customers.","두 말 모두 집에 돌아간 뒤 그 도시를 그리워하는 여행자를 가리킵니다. 다시 말해, 단골입니다.","게스트샷"),
("Kangfree","I'm a doctor. Not that kind. But I have a diagnosis: it's good for the Seoul.","저 박사예요. 그런 박사는 아니지만요. 그래도 진단은 있어요. 서울(Seoul)에는 약(soul에 좋다)이에요.","투샷. 자막에 Seoul / soul 말장난 강조"),
("K","Please don't.","제발 그러지 마세요.","투샷"),
("Kangfree","Seoul-searching. Seoul food. Seoul mate. I have a whole list.","소울 서칭, 소울 푸드, 소울 메이트. 목록이 한가득이에요.","큰 글자로 SEOUL-SEARCHING / SEOUL FOOD / SEOUL MATE 차례로 팝업"),
("Nonfic","For the record, I heard all of that. Now, rankings. Agoda's booking data for the first half of the year puts Seoul fourth in Asia for repeat visits.","참고로, 방금 건 다 들었습니다. 이제 순위입니다. 아고다의 상반기 예약 데이터에서 서울은 아시아 재방문 여행지 4위입니다.","게스트+화면: 순위 막대 1~5위 (Tokyo, Bangkok, Bali, Seoul, Osaka), 출처 AGODA"),
("Kangfree","Fourth! Who beat us?","4위요! 누가 우리를 이겼어요?","투샷"),
("Nonfic","Tokyo, Bangkok, and Bali. Osaka is fifth.","도쿄, 방콕, 발리입니다. 오사카가 5위예요.","게스트+화면: 순위 막대 1~3위 강조"),
("Kangfree","Fourth place. The saddest number at the Olympics.","4위. 올림픽에서 가장 슬픈 숫자죠.","투샷"),
("Nonfic","Analysts credit the range: K-content, festivals, food, beauty, shopping, and convenience stores that never close.","분석가들은 폭넓은 매력을 이유로 꼽습니다. K-콘텐츠, 축제, 음식, 뷰티, 쇼핑, 그리고 문 닫지 않는 편의점이요.","게스트+화면: 아이콘 6개 차례로 등장"),
("K","So the fever has a cause: a lot going on, and a snack at every hour.","그러니까 병에는 원인이 있네요. 할 게 많고, 아무 시간에나 간식이 있다는 거요.","투샷"),
("Kangfree","Symptoms include booking your second trip before the first one ends.","증상으로는 첫 여행이 끝나기 전에 두 번째 여행을 예약하는 것이 있어요.","투샷"),
("Nonfic","Treatment: none known.","치료법: 알려진 바 없음.","게스트샷"),
]),
("2. 지금 서울에서 볼 것 (Prof. Indoor 설명)", [
("K","If you catch it, where do you go? Our travel expert: Professor Indoor. Self-certified. Online.","걸렸다면 어디로 갈까요? 여행 전문가 Professor Indoor입니다. 자칭. 온라인으로.","게스트샷 하드 컷, 이름표"),
("Indoor","I've been there!","저 거기 가 봤어요!","게스트샷"),
("K","Physically?","몸으로요?","투샷"),
("Indoor","...Emotionally.","...마음으로요.","게스트샷"),
("Indoor","Okay, facts. Seoul is running a welcome campaign for tourists through October eleventh, with a help desk near Myeongdong Station that offers interpretation in English, Chinese, and Japanese.","좋아요, 사실입니다. 서울시는 10월 11일까지 관광객 환영 캠페인을 하고 있고, 명동역 근처 안내 데스크에서 영어, 중국어, 일본어 통역을 해 줍니다.","게스트+화면: 카드 SEOUL WELCOME WEEK 9/19–10/11, 지도 명동 핀 + 언어 3개 아이콘"),
("Kangfree","Help desks and interpreters. That's service.","안내 데스크에 통역까지. 서비스가 좋네요.","투샷"),
("Indoor","From October seventh to eleventh, the K-Royal Culture Festival turns the five grand palaces and Jongmyo Shrine into stages.","10월 7일부터 11일까지는 K-로열 문화 축제가 5대 궁과 종묘를 무대로 바꿉니다.","게스트+화면: 지도 5대 궁 + 종묘 핀"),
("Indoor","There is also a moonlight tour of Changdeokgung Palace, with sessions in English for foreign visitors.","창덕궁 달빛 기행도 있고, 외국인을 위한 영어 회차도 있어요.","게스트+화면: AI 일러스트 달빛 아래 궁궐"),
("Kangfree","A palace at night. That's so romantic.","밤의 궁궐이라니. 너무 낭만적이에요.","투샷"),
("Indoor","I watched the whole thing on a live stream. Best seat in the house. No line, no crowds, and the snacks are twelve feet away.","저는 전부 라이브로 봤어요. 가장 좋은 자리죠. 줄도 없고, 사람도 없고, 간식은 3.6미터 거리예요.","게스트샷"),
("K","That is... one way to travel.","그건... 여행하는 한 가지 방법이긴 하네요.","투샷"),
("Indoor","Now, the souvenir of the season: a cap. Seoul's city brand teamed up with a traditional-knot design brand, and one post about it got two point seven million views on Japanese social media. No ads.","이번 시즌 기념품은 모자예요. 서울시 브랜드가 전통 매듭 디자인 브랜드와 손잡았고, 그 게시물 하나가 일본 SNS에서 270만 조회를 기록했어요. 광고도 없이요.","게스트+화면: AI 일러스트 매듭 모자, 카운터 2.7M + NO ADS"),
("Kangfree","Let me guess. It's Seoul-d out.","맞혀 볼게요. 소울드 아웃(sold out, 매진)이죠.","투샷. 자막에 SEOUL-D OUT 강조"),
("Indoor","I wouldn't know. I've never been there.","저는 몰라요. 가 본 적이 없거든요.","게스트샷"),
("K","Emotionally?","마음으로는요?","투샷"),
("Indoor","Emotionally, I own three.","마음으로는 세 개 있어요.","게스트샷"),
]),
("3. 수출 사상 최대 (Max Rise)", [
("K","Now, another record. Max Rise, our money and business analyst.","이번엔 또 다른 기록입니다. 돈과 사업 담당 애널리스트, Max Rise입니다.","게스트샷 하드 컷, 이름표"),
("Rise","Good news. The line went up.","좋은 소식입니다. 그래프가 올랐어요.","게스트샷"),
("Rise","September exports: a hundred twenty-one billion dollars. A record. Up eighty-three percent.","9월 수출 1,210억 달러. 사상 최고. 83% 증가.","게스트+화면: 막대 66→121(십억 달러), +83.5%"),
("Kangfree","That's almost double!","거의 두 배잖아요!","투샷"),
("Rise","Chips did the heavy lifting. Over sixty billion dollars. Almost half of everything Korea sold.","칩이 힘든 일을 다 했습니다. 600억 달러 이상. 한국이 판 전체의 거의 절반입니다.","게스트+화면: 도넛 차트 반도체 ≈ 전체의 절반, +263%"),
("Kangfree","Finally, a chip Americans and Koreans both love.","드디어 미국인과 한국인이 둘 다 좋아하는 칩이 나왔네요.","투샷"),
("K","Different chips.","다른 칩이에요.","투샷"),
("Kangfree","Mine come with dip.","제 건 소스가 딸려 와요.","투샷"),
("Rise","AI is hungry. Korea makes the memory chips it eats. And Korean chips remember everything.","AI는 배고픕니다. 한국이 그게 먹는 메모리 칩을 만들죠. 그리고 한국 칩은 모든 걸 기억합니다.","게스트+화면: 데이터센터와 칩 일러스트"),
("Kangfree","Unlike me at the grocery store.","식료품점에서의 저와는 다르네요.","투샷"),
("Rise","Nine months in, Korea has already beaten all of last year. A trillion dollars is next. Limit up!","9개월 만에 한국은 이미 작년 한 해를 넘어섰습니다. 다음은 1조 달러. 상한가!","게스트+화면: 막대 2025 전체 vs 2026 1~9월 → 카운터 $1 TRILLION (효과음)"),
("Kangfree","A trillion! How many zeros is that?","1조 달러! 영이 몇 개예요?","투샷"),
("K","Twelve. Thank you for the math.","열두 개요. 계산 고마워요.","투샷"),
("Rise","Seoul fever. Chip fever. Limit up!","서울병. 반도체병. 상한가!","게스트샷"),
("Kangfree","Is there a cure?","치료법은 없어요?","투샷"),
("Rise","Not on my chart.","제 차트엔 없습니다.","게스트샷"),
]),
("4. 한글날 (Dr. H 설명)", [
("K","Next, a holiday you might not know: Hangul Day, October ninth. To explain it, our historian, Dr. H.","다음은 모를 수도 있는 휴일이에요. 10월 9일 한글날입니다. 설명해 줄 역사학자, Dr. H입니다.","카드: HANGUL DAY, OCT 9 → 게스트샷 하드 컷, 이름표"),
("Kangfree","Dr. H, what does the H stand for?","Dr. H, H는 뭐의 약자예요?","투샷"),
("Hidden","...That's classified.","...기밀입니다.","게스트샷 (속삭이는 톤)"),
("Hidden","Actually, Hangul Day is a public holiday. Korea takes a day off to celebrate its writing system.","사실 한글날은 공휴일입니다. 한국은 문자를 기념하려고 하루를 쉽니다.","게스트+화면: 카드 HANGUL DAY, 달력 OCT 9"),
("Kangfree","A holiday for an alphabet? In America, we just get a song.","알파벳을 위한 휴일이요? 미국에선 노래 하나가 전부인데.","투샷"),
("K","The ABC song is not a holiday.","ABC 송은 휴일이 아니에요.","투샷"),
("Kangfree","It should be. It has a really good tune.","그래야죠. 멜로디가 정말 좋잖아요.","투샷"),
("Hidden","Before the fourteen-forties, writing in Korea meant Chinese characters, and learning them took years.","1440년대 이전에 한국에서 글을 쓴다는 건 한자를 쓴다는 뜻이었고, 배우는 데 몇 년이 걸렸습니다.","게스트+화면: 한자 이미지 + 타임라인 ~1440"),
("Hidden","King Sejong the Great created Hangul in the fourteen-forties so that ordinary people could read and write.","세종대왕이 1440년대에 보통 사람들이 읽고 쓸 수 있도록 한글을 만들었습니다.","게스트+화면: 타임라인 1446 + 실루엣 일러스트"),
("Hidden","And here is the secret. The consonants copy the shape your mouth and tongue make when you say them.","그리고 비밀이 있습니다. 자음은 소리를 낼 때 입과 혀가 만드는 모양을 본떴습니다.","게스트+화면: 애니메이션 ㄱ ㄴ ㅁ 글자와 입 모양 단면도"),
("Kangfree","The letters are diagrams? So it's basically the first user-friendly interface.","글자가 그림 설명서라고요? 그럼 사실상 최초의 사용자 친화적 인터페이스네요.","투샷"),
("Hidden","Version one. Still no patch notes after five hundred eighty years.","버전 1. 580년이 지났는데 아직 패치 노트가 없습니다.","게스트+화면: 카운터 580 YEARS, 업데이트 아이콘에 X"),
("Hidden","Today it has twenty-four letters: fourteen consonants and ten vowels.","지금은 24자입니다. 자음 14개, 모음 10개.","게스트+화면: 카운터 14 + 10 = 24"),
("Kangfree","Learners say you can learn to read it in a day.","하루면 읽는 법을 배울 수 있다고들 해요.","투샷"),
("K","Let me test that. Write your name.","시험해 보죠. 이름을 써 보세요.","투샷"),
("Kangfree","Done!","다 썼어요!","한글로 쓴 이름 카드"),
("Hidden","It says \"Kang-peu-ri.\" Close enough.","\"강프리\"라고 쓰였네요. 그 정도면 됐습니다.","게스트샷"),
]),
("5. 빨리빨리, \"이거 한국에서 정상이야?\" 코너 (Ms. Nonfic 재등장)", [
("Kangfree","Time for a new segment: \"Is This Normal in Korea?\" Our expert witness is back: Ms. Nonfic.","새 코너 시간이에요. \"이거 한국에서 정상이야?\" 전문가 증인이 다시 나왔어요. Ms. Nonfic입니다.","코너 타이틀 카드 → 게스트샷 하드 컷, 이름표"),
("Nonfic","Exhibit A: the sidewalk. Everyone in Seoul walks like they're late for a flight. They might be.","증거 1번: 인도입니다. 서울에선 다들 비행기 놓칠 것처럼 걷습니다. 실제로 놓칠 수도 있고요.","게스트+화면: 큰 글자 EXHIBIT A, 빠르게 걷는 사람들 일러스트"),
("K","That's \"ppalli-ppalli.\" It means \"hurry, hurry.\"","\"빨리빨리\"예요. \"서두르자, 서두르자\"라는 뜻이죠.","카드: 빨리빨리 / PPALLI-PPALLI = HURRY, HURRY"),
("Nonfic","It's less a habit than an operating system. Delivery apps promise food in minutes. Some people press the elevator's close button before the doors finish opening.","습관이라기보다 운영체제에 가깝습니다. 배달 앱은 몇 분 안에 음식이 온다고 약속하고, 어떤 사람들은 엘리베이터 문이 다 열리기도 전에 닫힘 버튼을 누릅니다.","게스트+화면: 타이머 일러스트, 엘리베이터 닫힘 버튼이 반짝임"),
("Kangfree","They're not impatient. They're optimistic.","조급한 게 아니에요. 낙관적인 거죠.","투샷"),
("Nonfic","In America, you wait for the pizza. In Korea, the pizza waits for you.","미국에선 피자를 기다립니다. 한국에선 피자가 당신을 기다립니다.","게스트샷"),
("Kangfree","So, is this normal in Korea?","그래서 이게 한국에서 정상이에요?","투샷"),
("Nonfic","Verdict: normal. Please keep moving.","판정: 정상입니다. 계속 움직여 주세요.","게스트+화면: 도장 NORMAL ✔, 효과음"),
("K","Welcome to Korea.","한국에 오신 걸 환영합니다.","투샷"),
]),
("6. 왜 나이부터 물을까 (Ms. Nonfic 재등장)", [
("Kangfree","Last topic. A question every foreigner hears within five minutes.","마지막 주제예요. 외국인이 5분 안에 듣게 되는 질문이에요.","투샷"),
("K","\"How old are you?\"","\"몇 살이세요?\"","큰 글자 HOW OLD ARE YOU?"),
("Kangfree","In Korea, that's grammar.","한국에서는 그게 문법이에요.","투샷"),
("Nonfic","Korean has speech levels. To pick the right one, you need to know who is older. So the question is not nosy. It is a setting.","한국어에는 말투 단계가 있습니다. 알맞은 말투를 고르려면 누가 연장자인지 알아야 합니다. 그러니 그 질문은 참견이 아니라 설정값입니다.","게스트+화면: 말투 단계 사다리 그래픽"),
("Nonfic","Until 2023, Korea also had \"Korean age\": you are one at birth, and everyone gets a year older every January first. A baby born on December thirty-first turns two the next day.","2023년까지 한국에는 \"한국 나이\"도 있었습니다. 태어나면 한 살이고, 1월 1일마다 모두 한 살씩 늘어납니다. 12월 31일에 태어난 아기는 다음 날 두 살이 됩니다.","게스트+화면: 타임라인 애니메이션 12/31 출생=1세 → 1/1=2세"),
("Kangfree","Two days old and already two!","태어난 지 이틀인데 벌써 두 살이라니!","투샷"),
("Nonfic","In June 2023, Korea switched official documents to international age. Everyone became one or two years younger.","2023년 6월, 한국은 공식 문서의 나이를 만 나이로 통일했습니다. 모두가 한두 살씩 어려졌습니다.","게스트+화면: 카드 JUNE 2023"),
("Kangfree","Korea invented the cheapest anti-aging treatment in history: legislation.","한국이 역사상 가장 저렴한 노화 방지 치료를 발명했네요. 법률이요.","큰 글자 ANTI-AGING: LEGISLATION"),
("Nonfic","Social life did not change. People still ask.","사회생활은 바뀌지 않았습니다. 사람들은 여전히 묻습니다.","게스트샷"),
("Kangfree","One more thing. Koreans say \"our.\" Our mom, our house, our school. Even \"our wife.\"","하나 더요. 한국인은 \"우리\"라고 말해요. 우리 엄마, 우리 집, 우리 학교. 심지어 \"우리 아내\"까지요.","큰 글자 OUR 단어 모음"),
("Nonfic","\"Our\" signals belonging, not ownership. It means: we share this.","\"우리\"는 소유가 아니라 소속을 뜻합니다. 함께 나눈다는 의미입니다.","게스트샷"),
("Kangfree","So he's not sharing his wife. He's sharing the word.","그러니까 아내를 나눠 쓰는 게 아니라 단어를 나눠 쓰는 거네요.","투샷"),
("K","Please don't say that in English.","영어로는 제발 그렇게 말하지 마세요.","투샷"),
]),
("7. K's Take + 엔딩", [
("K","So here's my take. Fifteen million visitors, a record chip boom, an alphabet with its own holiday. Different stories, same pattern: the world is showing up for Korea.","제 생각은 이렇습니다. 방문객 1,500만 명, 사상 최대 반도체 호황, 휴일까지 있는 문자. 서로 다른 이야기지만 하나의 흐름이에요. 세계가 한국을 찾아오고 있다는 것.","투샷"),
("K","And Korea's answer is very Korean: \"Welcome. Our home is your home. Please hurry.\"","그리고 한국의 대답은 아주 한국적입니다. \"어서 오세요. 우리 집은 당신 집이에요. 서둘러 주세요.\"","투샷"),
("Kangfree","Tell us in the comments: what's the first thing you'd ask a Korean?","댓글로 알려 주세요. 한국 사람에게 제일 먼저 뭘 묻고 싶으세요?","투샷"),
("K","Subscribe, and we'll see you Wednesday. Stay curious. Keep your lenses clean.","구독하시고, 수요일에 만나요. 계속 궁금해하세요. 렌즈는 깨끗하게.","투샷"),
]),
]
